/*
 * Copyright 2015 FFY00.
 *
 * All Rights Reserved
 */
package pw.osiris.dev.LOGIN;

/**
 *
 * @author FFY00
 */
public class OsirisLoginGUI extends javax.swing.JPanel {
    // Bota "Invalid Password" escrito no label
    // errouPassword();
    public final static void errouPassword(){
        labelStatsPassword.setText("Invalid Password");
    }

    /**
     * Creates new form OsirisLoginGUI
     */
    public OsirisLoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
//GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        inputPassword = new javax.swing.JPasswordField();
        inputUser = new javax.swing.JFormattedTextField();
        labelPassword = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelStatsPassword = new javax.swing.JLabel();
        botaoLogin = new javax.swing.JButton();

        setName("OsirisBot - Login"); // NOI18N
        setOpaque(false);
        setRequestFocusEnabled(false);

        inputPassword.setText("password");
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });

        inputUser.setText("User");

        labelPassword.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        labelPassword.setText("Password:");

        labelUser.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        labelUser.setText("User:");

        labelTitulo.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        labelTitulo.setText("OsirisBot Login");

        labelStatsPassword.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        labelStatsPassword.setForeground(new java.awt.Color(224, 68, 68));
        labelStatsPassword.setText("");

        botaoLogin.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        botaoLogin.setText("Login");
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputUser, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelStatsPassword)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelStatsPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoLogin)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>
//GEN-END:initComponents

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // tODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    // Clicar no botao Login 
    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginActionPerformed
        // Muda a vairavel global pw.osiris.dev.VAR.GLOBAL.logado pra true e desbleia a main
        pw.osiris.dev.VAR.GLOBAL.logado = pw.osiris.dev.LOGIN.Login.autenticar(inputUser.toString(), inputPassword.toString());
        if(pw.osiris.dev.VAR.GLOBAL.logado == true){
            // Abre o GUI normal
            
        } else {
            // Bota "Invalid Password" escrito no label
            errouPassword();
        }
    }//GEN-LAST:event_botaoLoginActionPerformed

        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OsirisLoginGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OsirisLoginGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OsirisLoginGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OsirisLoginGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OsirisLoginGUI().setVisible(true);
            }
        });
    }
    
//GEN-BEGIN:variables
    // Variables declaration - do not modify
    private javax.swing.JButton botaoLogin;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JFormattedTextField inputUser;
    private javax.swing.JLabel labelPassword;
    private static javax.swing.JLabel labelStatsPassword;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUser;
    // End of variables declaration
//GEN-END:variables
}
